// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoPn6JpuKBAv5bWf38wvD4VWnHu7j-pGo',
    appId: '1:407157099726:web:83be490e0cc6c0ce09d49f',
    messagingSenderId: '407157099726',
    projectId: 'i-do-f0026',
    authDomain: 'i-do-f0026.firebaseapp.com',
    storageBucket: 'i-do-f0026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnB6P4LMiVQMEuSnzqleiaP9wC87ZbJL0',
    appId: '1:407157099726:android:74aa4168ca36736009d49f',
    messagingSenderId: '407157099726',
    projectId: 'i-do-f0026',
    storageBucket: 'i-do-f0026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-ZaEHnTutKp75qB0ZFuqNW6cPyjNPqFg',
    appId: '1:407157099726:ios:126eb9cfea5451fb09d49f',
    messagingSenderId: '407157099726',
    projectId: 'i-do-f0026',
    storageBucket: 'i-do-f0026.firebasestorage.app',
    iosBundleId: 'com.example.iDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-ZaEHnTutKp75qB0ZFuqNW6cPyjNPqFg',
    appId: '1:407157099726:ios:126eb9cfea5451fb09d49f',
    messagingSenderId: '407157099726',
    projectId: 'i-do-f0026',
    storageBucket: 'i-do-f0026.firebasestorage.app',
    iosBundleId: 'com.example.iDo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoPn6JpuKBAv5bWf38wvD4VWnHu7j-pGo',
    appId: '1:407157099726:web:20175266a102406609d49f',
    messagingSenderId: '407157099726',
    projectId: 'i-do-f0026',
    authDomain: 'i-do-f0026.firebaseapp.com',
    storageBucket: 'i-do-f0026.firebasestorage.app',
  );
}
